---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
library(ggplot2)
library(mice)
library(dplyr)
library(cowplot)


## Loading and preprocessing the data

activity<-read.csv("activity.csv")

## What is mean total number of steps taken per day?

echo=TRUE
steps<-tapply(activity$steps, activity$date, FUN=sum, na.rm=TRUE)
dates<-unique(activity$date)
stepssum<-data.frame(Steps=steps, Date=dates)

echo=TRUE
library(ggplot2)
a1<-ggplot(stepssum,aes(x= Steps))+
    geom_histogram(color="darkblue", fill="lightblue", position = "identity")+
    labs(y="Number of Days", title = "Total Number of Steps")+
    geom_vline(aes(xintercept=mean(stepssum$Steps)), size=1, linetype=3, color="#878787")+
    theme_bw()
a1
## What is the average daily activity pattern?
echo=TRUE
x<-mean(stepssum$Steps)
y<-median(stepssum$Steps)
paste("Mean:",x)
paste("Median:",y)


echo=TRUE
daily<-tapply(activity$steps, activity$interval, FUN = mean, na.rm=TRUE)
intervals<-unique(activity$interval)
avg<-data.frame(Steps=daily, Interval=intervals)
echo=TRUE
b<-ggplot(avg,aes(x=Interval,y=Steps))
b+geom_line(color="#553ea8", size=1)+
    labs(title = "Average Number of Steps by Interval")+
    theme_bw()
    echo=TRUE
y<-max(avg$Steps)
print(avg[which.max(avg$Steps) , ])


## Imputing missing values
echo=TRUE
sum(is.na(activity$steps)>0)
echo=TRUE
library(mice)
activity_numeric<-activity %>%
    select(steps, date, interval)

md.pattern(activity_numeric)

echo=TRUE
mice_imputed<- data.frame(
    original=activity$steps,
    imputed=complete(mice(activity_numeric,method = "pmm"))$steps,
    date = activity$date,
    interval = activity$interval
)
str(mice_imputed)
echo=TRUE
imsteps<-tapply(mice_imputed$imputed, mice_imputed$date, FUN=sum, na.rm=TRUE)
dates<-unique(mice_imputed$date)
imstepssum<-data.frame(imputed.Steps=imsteps, Date=dates)
head(imstepssum)
echo=TRUE
library(ggplot2)
a2<-ggplot(imstepssum,aes(x= imputed.Steps))+
    geom_histogram(color="darkred", fill="pink", position = "identity")+
    labs(y="Number of Days", title = "Total Number of Steps (Imputed)")+
    geom_vline(aes(xintercept=mean(imstepssum$imputed.Steps)), size=1, linetype=3, color="#878787")+
    theme_bw()
a2
echo=TRUE
library(cowplot)
plot_grid(a1,a2)
echo=TRUE
x<-mean(stepssum$Steps)
y<-median(stepssum$Steps)
m<-mean(imstepssum$imputed.Steps)
n<-median(imstepssum$imputed.Steps)
z<-data.frame(Mean=c(x,m),Median=c(y,n))
row.names(z)<-c("Original","Imputed")
z

## Are there differences in activity patterns between weekdays and weekends?
echo=TRUE
mice_imputed$date<-as.Date(mice_imputed$date)
Day<-weekdays(mice_imputed$date)
mice_imputed<-cbind(mice_imputed,Day)
mice_imputed<-mutate(mice_imputed, Weekday = ifelse(Day=="Monday"|Day=="Tuesday"|Day=="Wednesday"|Day=="Thursday"|Day=="Friday","Y","N"))
str(mice_imputed)
echo=TRUE
MF<-subset(mice_imputed, Weekday=="Y")
SS<-subset(mice_imputed, Weekday=="N")
echo=TRUE
sumMF<-tapply(MF$imputed, MF$interval, FUN = mean, na.rm=TRUE)
intervals<-unique(MF$interval)
avgMF<-data.frame(Steps=sumMF, Interval=intervals)

sumSS<-tapply(SS$imputed, SS$interval, FUN = mean, na.rm=TRUE)
avgSS<-data.frame(Steps=sumSS, Interval=intervals)
echo=TRUE
w1<-ggplot(avgMF,aes(x=Interval,y=Steps))+
    geom_line(color="#ff9354", size=1)+
    labs(title = "Average Weekday")+
    
    theme_bw()

w2<-ggplot(avgSS,aes(x=Interval,y=Steps))+
    geom_line(color="#54f0ac", size=1)+
    labs(title = "Average Weekend")+
    theme_bw()

plot_grid(w1,w2)